apiVersion: v1
kind: Service
metadata:
  name: fastify-api-service
  labels:
    app: api-fastify
  namespace: simulador-fin
spec:
  selector:
    app: api-fastify
  ports:
  - port: 80
    name: http
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
