version: '3.8'

services:
  nodejs:
    container_name: api-financing-simulator
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    expose:
      - 3000
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    command: sh -c "npm run start:docker"

  postgres:
    container_name: alume_db
    image: postgres:17.5-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alume_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: