apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: simulador-fin
spec:
  selector:
    app: frontend-simulador-fin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
