name: Backend CD

on:
  push:
    paths:
      - 'backend/**'
      - '!frontend/**'
    branches:
      - main

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: matheusgomesa/financing-simulator:${{ github.run_id }}

  # deploy:
  #   runs-on: [self-hosted, k8s]
  #   needs: docker-build-push
  #   if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'pull_request' && github.event.pull_request.merged == true }}
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v4

  #     - name: Atualiza tag da imagem no deployment
  #       run: |
  #         sed "s/\$IMAGE_TAG/${{ github.run_id }}/g" k8s/backend/deployment.yml > k8s/backend/deployment-temp.yml

  #     - name: Set script permissions
  #       run: chmod +x ./deploy-backend.sh

  #     - name: Deploy Backend
  #       run: ./deploy-backend.sh
