name: Backend CD

on:
  push:
    paths:
      - 'backend/**'
      - '!frontend/**'
    branches:
      - main

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: matheusgomesa/financing-simulator:${{ github.run_id }}

  deploy:
    runs-on: [self-hosted, k8s]
    needs: docker-build-push
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Atualiza tag da imagem no deployment
        run: |
          sed "s/\$IMAGE_TAG/${{ github.run_id }}/g" k8s/backend/deployment.yml > k8s/backend/deployment-temp.yml
          mv k8s/backend/deployment-temp.yml k8s/backend/deployment.yml

      - name: Set script permissions
        run: chmod +x ./k8s/deploy-backend.sh

      - name: Deploy Backend
        env:
          PORT: ${{ vars.PORT || '3000' }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRATION: ${{ vars.JWT_EXPIRATION || '24h' }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: ./k8s/deploy-backend.sh